name: Run on Label Assignment (finish hackpod)

on:
  issues:
    types:
      - labeled

jobs:
  run_on_label_assignment:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Repository
      uses: actions/checkout@v2

    - name: Install
      run: npm install
      working-directory: ./roiScript

    - name: Run script on label assignment
      if: contains(github.event.issue.labels.*.name, 'completed hackpod issue') # no way to set a particular label workflow trigger -- https://github.com/orgs/community/discussions/26261
      run: node ./roiScript/send-metrics.mjs
